// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDam1sSLOcAFrF98k5g10MLHS8Avs5Acp8',
    appId: '1:484558690842:web:c8c4dad2ebc53d9b5f4fa3',
    messagingSenderId: '484558690842',
    projectId: 'warning-software-stroke',
    authDomain: 'warning-software-stroke.firebaseapp.com',
    databaseURL: 'https://warning-software-stroke-default-rtdb.firebaseio.com',
    storageBucket: 'warning-software-stroke.firebasestorage.app',
    measurementId: 'G-87C0CGT30P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc2rnas6kGOJGqQ4CgJGCSL6-qZM0SoT0',
    appId: '1:484558690842:android:0145c3822607f9f05f4fa3',
    messagingSenderId: '484558690842',
    projectId: 'warning-software-stroke',
    databaseURL: 'https://warning-software-stroke-default-rtdb.firebaseio.com',
    storageBucket: 'warning-software-stroke.firebasestorage.app',
  );

}